#!/usr/bin/env bash
set -euo pipefail

mkdir -p -- TODO
mkdir -p -- ai_ck
mkdir -p -- ai_hive
mkdir -p -- case_studies
mkdir -p -- da_assets
mkdir -p -- data_agent_plan
mkdir -p -- eval
mkdir -p -- examples
mkdir -p -- knowledge
mkdir -p -- semantic_model
mkdir -p -- showoff
mkdir -p -- skills
mkdir -p -- tools
mkdir -p -- '关键问题记录'
mkdir -p -- 'TODO/ai_hive待回填'
mkdir -p -- ai_ck/business_profiles
mkdir -p -- ai_ck/metrics
mkdir -p -- ai_ck/queries
mkdir -p -- ai_ck/schema
mkdir -p -- ai_ck/schema_exports
mkdir -p -- ai_ck/table_profiles
mkdir -p -- ai_ck/tables
mkdir -p -- ai_ck/business_profiles/samples
mkdir -p -- ai_ck/queries/verified
mkdir -p -- ai_ck/table_profiles/_raw_dump
mkdir -p -- ai_hive/evidence
mkdir -p -- ai_hive/schema
mkdir -p -- ai_hive/tables
mkdir -p -- ai_hive/evidence/ods_market_google_ads_config_wide_hi
mkdir -p -- case_studies/mi_roi360_board_recon
mkdir -p -- case_studies/wide_hi
mkdir -p -- case_studies/mi_roi360_board_recon/docs
mkdir -p -- case_studies/mi_roi360_board_recon/scripts
mkdir -p -- case_studies/mi_roi360_board_recon/sql
mkdir -p -- case_studies/wide_hi/assets
mkdir -p -- case_studies/wide_hi/docs
mkdir -p -- case_studies/wide_hi/sql
mkdir -p -- da_assets/analysis_sop
mkdir -p -- da_assets/candidate_sql
mkdir -p -- da_assets/decision_cases
mkdir -p -- da_assets/verified_sql
mkdir -p -- data_agent_plan/docx_report_intake_skill
mkdir -p -- eval/agent_regression
mkdir -p -- examples/audience
mkdir -p -- examples/audience/sql
mkdir -p -- knowledge/draft_knowledge
mkdir -p -- knowledge/mi_analysis
mkdir -p -- knowledge/policies
mkdir -p -- knowledge/prompts
mkdir -p -- knowledge/reconciliations
mkdir -p -- knowledge/report_knowledge
mkdir -p -- semantic_model/eval
mkdir -p -- 'skills/docx报告入库技能'
mkdir -p -- skills/mi_skill
mkdir -p -- tools/dist
mkdir -p -- tools/runbooks
mkdir -p -- tools/scripts
mkdir -p -- tools/dist/payload
mkdir -p -- tools/dist/payload/bin
mkdir -p -- tools/dist/payload/env
mkdir -p -- tools/dist/payload/skills
mkdir -p -- tools/dist/payload/skills/clickhouse-shucang
mkdir -p -- tools/dist/payload/skills/maxcompute-dataworks
mkdir -p -- tools/dist/payload/skills/mi-roi360-analysis
